login completo
ediaz2/ecotop-back pull request #4
Opened 2022-03-08 05:00 UTC by Jaqueline0220

- **¿Qué módulo se trabajo?**

- **¿Qué tipo de cambio introduce este PR?**

* [ ] [feat] : Features
* [ ] [fix] : Bug Fixes

- **¿Este PR introduce un cambio radical?**
  BREAKING CHANGE:

2022-03-09 12:26 UTC, Drleugim requested changes
Please review comments and make changes. Otherwise it's a really good PR. Thanks!

2022-03-09 12:26 UTC, Drleugim commented on src/controllers/auth.js
> +    /*const authUpdate = await Auth.findByIdAndUpdate(body.id, body, {
Please remove commented code

2022-03-09 12:26 UTC, Drleugim commented on src/controllers/tipoDocumento.js
> +    next(err);
No t necessary to change, but sometimes it is good to `throw` an error, instead of simple letting the logic continue

2022-03-12 00:56 UTC, Jaqueline0220 commented on src/controllers/auth.js
> +    /*const authUpdate = await Auth.findByIdAndUpdate(body.id, body, {
Listo, se elimino el bloque de código comentado

2022-03-14 22:00 UTC, Drleugim requested changes

2022-03-14 22:00 UTC, Drleugim commented on src/routes/users.js
> +//const { checkJwt } = require('../middlewares');
remove commented code

2022-03-15 01:45 UTC, Jaqueline0220 commented on src/routes/users.js
> +//const { checkJwt } = require('../middlewares');
Listo !!

2022-03-16 08:14 UTC, Drleugim approved these changes
Error handling could still improve. But LGTM

2022-03-16 08:14 UTC, Drleugim commented on src/controllers/auth.js
> +    if (!user) throw new NotFoundException(mensaje.loginUser, 'auth');
Not a fan of one line `if` statements but it's not necessary to change

2022-03-17 05:22 UTC, merged